/*******************************************************************************
 * Copyright (c) 2025 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.tools.serverboot;

import java.io.IOException;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.filter.OncePerRequestFilter;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpServletResponseWrapper;

class ErrorLoggingFilter extends OncePerRequestFilter {

	private static final Logger logger = LoggerFactory.getLogger(ErrorLoggingFilter.class);

	@Override
	protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
			throws ServletException, IOException {
		StatusCapturingResponseWrapper responseWrapper = new StatusCapturingResponseWrapper(response);
		boolean logged = false;
		try {
			filterChain.doFilter(request, responseWrapper);
		} catch (Exception ex) {
			logged = true;
			logEvent(request, responseWrapper.getStatus(), ex);
			throw ex;
		} finally {
			if (!logged) {
				logEvent(request, responseWrapper.getStatus(), null);
			}
		}
	}

	private void logEvent(HttpServletRequest request, int status, Exception error) {
		if (error == null && status < HttpServletResponse.SC_BAD_REQUEST) {
			return;
		}
		StringBuilder target = new StringBuilder(request.getMethod()).append(' ').append(request.getRequestURI());
		Optional.ofNullable(request.getQueryString()).ifPresent(query -> target.append('?').append(query));
		target.append(" from ").append(request.getRemoteAddr());
		Optional.ofNullable(request.getHeader("User-Agent"))
				.ifPresent(agent -> target.append(" UA=\"").append(agent).append('"'));

		if (error != null || status >= HttpServletResponse.SC_INTERNAL_SERVER_ERROR) {
			logger.error("HTTP {} {}", status, target, error);
		} else {
			logger.warn("HTTP {} {}", status, target);
		}
	}

	private static final class StatusCapturingResponseWrapper extends HttpServletResponseWrapper {

		private int status = HttpServletResponse.SC_OK;

		StatusCapturingResponseWrapper(HttpServletResponse response) {
			super(response);
		}

		@Override
		public void sendError(int sc) throws IOException {
			this.status = sc;
			super.sendError(sc);
		}

		@Override
		public void sendError(int sc, String msg) throws IOException {
			this.status = sc;
			super.sendError(sc, msg);
		}

		@Override
		public void setStatus(int sc) {
			this.status = sc;
			super.setStatus(sc);
		}

		@Override
		public void sendRedirect(String location) throws IOException {
			this.status = HttpServletResponse.SC_FOUND;
			super.sendRedirect(location);
		}

		@Override
		public int getStatus() {
			return status;
		}
	}
}
